language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install --prefer-source --no-interaction

script:
  - phpunit --coverage-text

